name: TESTE 2

on:
  push:
  
jobs:
  checkout_code:
    name: Do checkout code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Upload a build Artfact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ vars.TESTEVAR }}
          path: .
  
